name: ReviewDog Base
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: ReviewDog Base
    runs-on: ubuntu-latest

steps:
  - uses: reviewdog/action-setup@v1
    with:
      reviewdog_version: v0.14.1
  - run: reviewdog -version